-- MySQL Script generated by MySQL Workbench
-- Sat Sep  7 18:11:40 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema PhoneBookEntry
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema PhoneBookEntry
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `PhoneBookEntry` DEFAULT CHARACTER SET utf8 ;
USE `PhoneBookEntry` ;

-- -----------------------------------------------------
-- Table `PhoneBookEntry`.`PhoneBook`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `PhoneBookEntry`.`PhoneBook` ;

CREATE TABLE IF NOT EXISTS `PhoneBookEntry`.`PhoneBook` (
  `PhoneBookId` CHAR(36) NOT NULL,
  `Name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`PhoneBookId`),
  UNIQUE INDEX `id_UNIQUE` (`PhoneBookId` ASC) VISIBLE,
  UNIQUE INDEX `Name_UNIQUE` (`Name` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `PhoneBookEntry`.`Entry`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `PhoneBookEntry`.`Entry` ;

CREATE TABLE IF NOT EXISTS `PhoneBookEntry`.`Entry` (
  `EntryId` CHAR(36) NOT NULL,
  `Name` NVARCHAR(60) NOT NULL,
  `PhoneNumber` VARCHAR(10) NOT NULL,
  `PhoneBookId` CHAR(36) NOT NULL,
  PRIMARY KEY (`EntryId`),
  UNIQUE INDEX `id_UNIQUE` (`EntryId` ASC) VISIBLE,
  UNIQUE INDEX `PhoneNumber_UNIQUE` (`PhoneNumber` ASC) VISIBLE,
  INDEX `fk_Entry_PhoneBook_idx` (`PhoneBookId` ASC) VISIBLE,
  CONSTRAINT `fk_Entry_PhoneBook`
    FOREIGN KEY (`PhoneBookId`)
    REFERENCES `PhoneBookEntry`.`PhoneBook` (`PhoneBookId`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
